Repository bevyengine/bevy-website, pull requests merged in 2023-03, with the labels that each got.

#597 Enable merge queues in CI jobs
  .github/workflows/ci.yml
Labels: A-Build-System

#592 I'm -> we're in 0.10 release post
  content/news/2023-03-06-bevy-0.10/index.md
Labels: C-Bug, A-News

#600 on_enter and on_exit are not a thing
  content/learn/book/migration-guides/0.9-0.10/_index.md
Labels: C-Bug, S-Ready-For-Final-Review, A-News

#604 Improve 0.9 -> 0.10 scheduling migration advice
  content/learn/book/migration-guides/0.9-0.10/_index.md
Labels: S-Ready-For-Final-Review, A-News, C-Content

#606 Fix links to migration guides in news posts
  content/news/2021-04-06-bevy-0.5/index.md
  content/news/2022-01-08-bevy-0.6/index.md
  content/news/2022-04-15-bevy-0.7/index.md
  content/news/2022-07-30-bevy-0.8/index.md
  content/news/2022-11-12-bevy-0.9/index.md
  content/news/2023-03-06-bevy-0.10/index.md
Labels: C-Bug, S-Ready-For-Final-Review, C-Webdev

#611 Remove "book FAQ"
  content/faq/index.md
  content/learn/book/faq/_index.md
Labels: S-Blocked

#614 Fix typo
  content/learn/migration-guides/0.9-0.10/_index.md
Labels: C-Bug, S-Ready-For-Final-Review, A-News

#581 Fix cards responsive issues
  content/community/links.toml
  content/learn/links.toml
  sass/_mixins.scss
  sass/_vars.scss
  sass/components/_asset-card.scss
  sass/components/_card.scss
  sass/components/_item-grid.scss
  sass/components/_link-card.scss
  sass/pages/_community.scss
  sass/site.scss
  static/assets/people.svg
  templates/assets.html
  templates/community.html
  templates/donate.html
  templates/examples.html
  templates/learn.html
  templates/news.html
  templates/people.html
Labels: C-Bug, C-Webdev
