Repository bevyengine/bevy-website, pull requests merged in 2024-05, with the labels that each got.

#1142 add `cursor: pointer` to details summary
  sass/elements/_details.scss
  sass/site.scss
Labels: S-Ready-For-Final-Review, C-Webdev, C-Usability

#1129 bypass the loading bar as much as possible for 404s
  static/tools.js
Labels: S-Ready-For-Final-Review, C-Webdev, A-Examples

#1145 correct name of the dynamic_linking feature
  content/learn/book/development-practices/fast-compiles.md
Labels: S-Ready-For-Final-Review, A-Book, C-Correction

#1084 Cancel in progress CI jobs on PRs
  .github/workflows/ci.yml
Labels: C-Enhancement, S-Ready-For-Final-Review, A-Build-System

#1144 Add a shortcode for the image compare slider
  content/news/2023-07-09-bevy-0.11/aa.png
  content/news/2023-07-09-bevy-0.11/index.md
  content/news/2023-07-09-bevy-0.11/msaa_helmet.png
  content/news/2023-07-09-bevy-0.11/taa_helmet.png
  content/news/2023-11-04-bevy-0.12/index.md
  content/news/2024-02-17-bevy-0.13/index.md
  sass/components/_image_compare.scss
  static/components.js
  templates/shortcodes/compare_slider.html
Labels: S-Ready-For-Final-Review, A-News, C-Webdev

#1150 Fix docs footer navigation
  templates/docs-base.html
Labels: C-Bug, S-Ready-For-Final-Review, A-Book, C-Webdev

#1152 Phase 1 of Contributor's Guide – Foundational Folder
  content/contributing/_index.md
  templates/layouts/base.html
Labels: C-Enhancement, S-Ready-For-Final-Review

#1153 Tweak `tree-menu` styling
  sass/components/_tree-menu.scss
Labels: C-Enhancement, S-Ready-For-Final-Review, C-Webdev

#1154 add aria-label to image compare slider
  static/components.js
Labels: C-Enhancement, C-Accessibility, S-Ready-For-Final-Review, C-Webdev

#1078 Improve LLD fast compile instructions
  content/learn/quick-start/getting-started/setup.md
Labels: S-Ready-For-Final-Review, A-Book, C-Content

#545 Add tonemapping example images for use in the book and rustdoc
  static/assets-docs/README.md
  static/assets-docs/tonemapping/README.md
  static/assets-docs/tonemapping/aces_fitted.png
  static/assets-docs/tonemapping/agx.png
  static/assets-docs/tonemapping/blender_filmic.png
  static/assets-docs/tonemapping/disabled.png
  static/assets-docs/tonemapping/reinhard.png
  static/assets-docs/tonemapping/reinhard_luminance.png
  static/assets-docs/tonemapping/sbdt.png
  static/assets-docs/tonemapping/tonymcmapface.png
Labels: S-Ready-For-Final-Review, A-Book, C-Webdev

#1130 Use nouns in singular form to match the corresponding data types
  content/learn/quick-start/getting-started/apps.md
  content/learn/quick-start/getting-started/plugins.md
  content/learn/quick-start/getting-started/resources.md
Labels: S-Ready-For-Final-Review, A-Book, C-Correction

#1132 Corrected code breaking syntax corrections 0.12-to-0.13.md
  content/learn/migration-guides/0.12-to-0.13.md
Labels: S-Ready-For-Final-Review, A-Migration Guides, C-Correction

#1141 add linux dependency instructions and some placeholder headers
  content/learn/book/getting-started/installation.md
Labels: S-Ready-For-Final-Review, A-Book, C-Content

#1155 add more styles to <details>
  sass/elements/_details.scss
Labels: S-Ready-For-Final-Review, C-Webdev

#1156 Show the mobile header on tablet-landscape
  sass/_vars.scss
  sass/components/_header.scss
  sass/components/_logo.scss
  sass/components/_main-menu.scss
Labels: C-Enhancement, S-Ready-For-Final-Review, C-Webdev

#1149 Merge `docs-section`/`docs-page` templates into `docs`
  content/contributing/_index.md
  content/learn/advanced-examples/_index.md
  content/learn/advanced-examples/sudoku/_index.md
  content/learn/advanced-examples/text-adventure/_index.md
  content/learn/book/_index.md
  content/learn/book/assets/_index.md
  content/learn/book/audio/_index.md
  content/learn/book/development-practices/_index.md
  content/learn/book/ecs/_index.md
  content/learn/book/game-logic/_index.md
  content/learn/book/getting-started/_index.md
  content/learn/book/graphics/2d/_index.md
  content/learn/book/graphics/3d/_index.md
  content/learn/book/graphics/_index.md
  content/learn/book/graphics/rendering-internals/_index.md
  content/learn/book/input/_index.md
  content/learn/book/performance-optimizations/_index.md
  content/learn/book/platforms/_index.md
  content/learn/book/ui/_index.md
  content/learn/migration-guides/_index.md
  content/learn/quick-start/3d-puzzle-game/_index.md
  content/learn/quick-start/_index.md
  content/learn/quick-start/breakout/_index.md
  content/learn/quick-start/falling-sand/_index.md
  content/learn/quick-start/getting-started/_index.md
  generate-errors/src/lib.rs
  templates/docs-page.html
  templates/docs-section.html
  templates/docs.html
  templates/layouts/base.html
Labels: A-Book, C-Webdev, C-Code Quality

#1162 Add custom `atom.xml` template to hide public draft news articles
  templates/atom.xml
Labels: C-Bug, S-Ready-For-Final-Review, A-News

#1147 Add "On This Page" navigation
  sass/components/_on-this-page.scss
  sass/components/_tree-menu.scss
  sass/site.scss
  static/on-this-page.js
  templates/docs.html
  templates/macros/docs.html
Labels: C-Enhancement, S-Ready-For-Final-Review, A-Book, C-Webdev

#1161 Update macOS linking advice
  content/learn/quick-start/getting-started/setup.md
Labels: S-Ready-For-Final-Review, A-Book, C-Correction

#1164 Minor On This Page Script Changes
  static/on-this-page.js
Labels: S-Ready-For-Final-Review, C-Webdev, C-Code Quality

#1157 create logging page
  content/learn/book/development-practices/logging.md
Labels: S-Ready-For-Final-Review, A-Book, C-Content

#1167 Add `callout` shortcode
  content/learn/quick-start/getting-started/_index.md
  content/learn/quick-start/introduction.md
  sass/components/_callout.scss
  sass/site.scss
  templates/shortcodes/callout.html
Labels: S-Ready-For-Final-Review, A-Book, C-Webdev

#1168 Change homepage `Get Started` link so that users don't miss the "Stability Warning"
  templates/index.html
Labels: S-Ready-For-Final-Review, A-Quick-Start, S-Needs-Review

#1166 Add `--font-family-*` tokens
  sass/_vars.scss
  sass/elements/_html.scss
  sass/fonts/_firamono.scss
  sass/pages/_content.scss
Labels: C-Bug, S-Ready-For-Final-Review, C-Webdev, C-Code Quality

#1169 Change callout from div to aside
  templates/shortcodes/callout.html
Labels: S-Ready-For-Final-Review, C-Webdev, C-Code Quality

#1165 Generate multiple files for migration guide
  generate-release/.gitignore
  generate-release/src/changelog.rs
  generate-release/src/helpers.rs
  generate-release/src/main.rs
  generate-release/src/markdown.rs
  generate-release/src/migration_guide.rs
  generate-release/src/migration_guides.rs
  generate-release/src/release_notes.rs
  generate-release/src/release_notes_website.rs
  templates/docs.html
  templates/macros/migration_guides.html
  templates/migration_guides.html
Labels: C-Enhancement, S-Ready-For-Final-Review, A-Build-System, A-Migration Guides

#1174 Fix doc pages title with special characters
  templates/docs.html
Labels: C-Bug, S-Ready-For-Final-Review, A-Book, A-Migration Guides

#1171 Fix TOC overflow in Migration Guides
  sass/components/_on-this-page.scss
  sass/components/_tree-menu.scss
Labels: C-Bug, S-Ready-For-Final-Review, C-Webdev, A-Migration Guides

#1175 Increase TOC spacing between entries
  sass/components/_on-this-page.scss
Labels: S-Ready-For-Final-Review, A-Book, C-Webdev, C-Usability, A-Migration Guides, A-Quick-Start

#1176 Change text colors for "On This Page" section
  sass/components/_on-this-page.scss
Labels: S-Ready-For-Final-Review, A-Book, C-Webdev, A-Migration Guides, A-Quick-Start

#1177 Increase TOC spacing between entries (again)
  sass/components/_on-this-page.scss
Labels: S-Ready-For-Final-Review, A-Book, C-Webdev, A-Migration Guides, A-Quick-Start

#1182 add print styling
  sass/_print.scss
  sass/site.scss
  templates/docs.html
  templates/layouts/base.html
  templates/layouts/page-with-menu.html
Labels: C-Enhancement, C-Accessibility, S-Ready-For-Final-Review, C-Webdev, C-Usability

#1170 Fix On This Page algorithm
  sass/components/_on-this-page.scss
  static/on-this-page.js
  templates/macros/docs.html
Labels: C-Bug, S-Ready-For-Final-Review, C-Webdev

#1179 Hard-code possible docs template root sections
  templates/docs.html
  templates/layouts/base.html
Labels: C-Bug, C-Enhancement, S-Ready-For-Final-Review, A-Book, C-Webdev, A-Migration Guides, A-Quick-Start

#1172 Add tool to generate changelog, contributors and release notes
  Cargo.lock
  generate-release/Cargo.toml
  generate-release/README.md
  generate-release/src/changelog.rs
  generate-release/src/contributors.rs
  generate-release/src/github_client.rs
  generate-release/src/helpers.rs
  generate-release/src/main.rs
  generate-release/src/migration_guides.rs
  generate-release/src/release_notes.rs
  generate-release/src/release_notes_website.rs
  sass/components/_pr-list.scss
  sass/site.scss
  templates/macros/migration_guides.html
  templates/macros/path.html
  templates/migration_guides.html
  templates/news-page.html
  templates/shortcodes/changelog.md
  templates/shortcodes/contributors.md
  templates/shortcodes/load_markdown.md
  templates/shortcodes/migration_guides.md
  templates/shortcodes/release_notes.md
  templates/shortcodes/support_bevy.md
Labels: A-Build-System, A-Release-Notes, S-Needs-Review

#1186 Add more info about public_draft in the generate-release README
  generate-release/README.md
Labels: S-Ready-For-Final-Review, A-Build-System, A-Release-Notes

#1184 Fix default version filter
  static/assets.js
Labels: C-Bug, S-Ready-For-Final-Review, A-Assets, C-Webdev

#1194 Generate authors list for release notes
  generate-release/src/migration_guides.rs
  generate-release/src/release_notes.rs
  sass/pages/_news.scss
  templates/shortcodes/release_notes.md
Labels: C-Enhancement, S-Ready-For-Final-Review, A-Release-Notes

#1178 Contributor's Guide: Create "Using Github Issues"
  content/contributing/getting-started/_index.md
  content/contributing/getting-started/using-github-issues.md
  content/contributing/reference/_index.md
  content/contributing/reference/triage.md
Labels: S-Ready-For-Final-Review, C-Content, A-Contributing-Guide

#1199 Add initial What's Next section to Bevy 0.14 notes
  content/news/draft-bevy-0.14/index.md
Labels: S-Ready-For-Final-Review, C-Content, A-Release-Notes

#1196 Normalize migration guide whitespace
  generate-release/src/migration_guides.rs
Labels: C-Enhancement, S-Ready-For-Final-Review, A-Build-System, A-Migration Guides

#1197 Remove confusing logging about "migration guide not found"
  generate-release/src/markdown.rs
Labels: S-Ready-For-Final-Review, A-Build-System, C-Usability

#1201 Release notes for working groups
  release-content/0.14/release-notes/13162_Add_a_process_for_working_groups.md
  release-content/0.14/release-notes/_release-notes.toml
Labels: S-Ready-For-Final-Review, C-Content, A-Release-Notes, S-Needs-Review

#1198 Add initial intro for Bevy 0.14 release notes
  content/news/draft-bevy-0.14/index.md
Labels: S-Ready-For-Final-Review, C-Content, A-Release-Notes

#1203 Cut some unhelpful release notes
  release-content/0.14/release-notes/11904_Add_support_for_KHR_texture_transform.md
  release-content/0.14/release-notes/12147_bevy_color_Added_Color_Conversion_Mermaid_Diagram.md
  release-content/0.14/release-notes/12163_Migrate_from_LegacyColor_to_bevy_colorColor.md
  release-content/0.14/release-notes/12331_We_must_have_googly_eyes_new_Game_example.md
  release-content/0.14/release-notes/12550_Use_asyncfn_in_traits_rather_than_BoxedFuture.md
  release-content/0.14/release-notes/12686_Meshing_for_Triangle3d_primitive.md
  release-content/0.14/release-notes/12734_Meshing_for_Annulus_primitive.md
  release-content/0.14/release-notes/9202_Refactor_App_and_SubApp_internals_for_better_separation.md
  release-content/0.14/release-notes/_release-notes.toml
Labels: S-Ready-For-Final-Review, C-Content, A-Release-Notes

#1202 Release notes for bevy_color
  release-content/0.14/release-notes/12013_Upstreaming_bevy_color.md
  release-content/0.14/release-notes/_release-notes.toml
Labels: S-Ready-For-Final-Review, C-Content, A-Release-Notes

#1206 Remove bevy_dev_tools from release notes
  release-content/0.14/release-notes/11341_Add_bevy_dev_tools_crate.md
  release-content/0.14/release-notes/_release-notes.toml
Labels: A-Release-Notes

#1205 Initial release notes for computed and substates
  release-content/0.14/release-notes/11426_Computed_State__Sub_States.md
  release-content/0.14/release-notes/_release-notes.toml
Labels: S-Ready-For-Final-Review, C-Content, A-Release-Notes

#1207 Write up dev tools abstraction future work
  content/news/draft-bevy-0.14/index.md
Labels: C-Content, A-Release-Notes, S-Needs-Review

#1215 Generate a comment with PR link for release notes
  generate-release/src/release_notes.rs
Labels: S-Ready-For-Final-Review, A-Build-System, A-Release-Notes

#1210 Write up deprecate dynamic plugins
  release-content/0.14/release-notes/13080_Deprecate_dynamic_plugins.md
Labels: S-Ready-For-Final-Review, C-Content, A-Release-Notes

#1218 fixedbitset 0.5 migration guide
  release-content/0.14/migration-guides/12512_Update_to_fixedbitset_05.md
  release-content/0.14/migration-guides/12512_update_to_fixedbitset_05.md
  release-content/0.14/migration-guides/_guides.toml
Labels: C-Content, A-Migration Guides

#1221 show [DRAFT] in the <title> of draft pages
  templates/layouts/base.html
Labels: S-Ready-For-Final-Review, A-Book, C-Webdev, A-Release-Notes

#1217 `Node2d` migration guide
  release-content/0.14/migration-guides/12038_fix_node2d_typo.md
  release-content/0.14/migration-guides/12038_fix_some_typos.md
  release-content/0.14/migration-guides/_guides.toml
  typos.toml
Labels: S-Ready-For-Final-Review, C-Content, A-Migration Guides

#1214 Add render graph rewrite to What's Next
  content/news/draft-bevy-0.14/index.md
Labels: S-Ready-For-Final-Review, A-Release-Notes

#1223 Move public draft meta tags to base template
  templates/docs.html
  templates/layouts/base.html
Labels: C-Bug, S-Ready-For-Final-Review, C-Webdev

#1268 Clean up state-related migration guides
  release-content/0.14/migration-guides/11426_Computed_State__Sub_States.md
  release-content/0.14/migration-guides/12997_multi_threaded_feature_rename.md
  release-content/0.14/migration-guides/13216_Separate_state_crate.md
Labels: S-Ready-For-Final-Review, C-Content, A-Migration Guides
