Repository bevyengine/bevy-website, pull requests merged in 2024-12, with the labels that each got.

#1893 Fix sorting of patch version numbers in crates.io metadata retrieval
  generate-assets/src/lib.rs
Labels: C-Bug, S-Ready-For-Final-Review, A-Assets

#1909 Fix sidebar section highlighter
  static/on-this-page.js
Labels: C-Bug, C-Webdev, D-Straightforward

#1906 Hide heading anchors by default
  sass/_utils.scss
Labels: C-Feature, C-Webdev, D-Trivial

#1907 Use `<hr>` instead of `border-top` in Migration headings
  sass/pages/_migration_guide.scss
  templates/shortcodes/migration_guides.md
Labels: C-Bug, S-Ready-For-Final-Review, C-Webdev, A-Migration Guides, D-Trivial

#1904 add slash to route
  templates/macros/header.html
Labels: C-Webdev, S-Needs-Review, A-Cross-Cutting

#1902 Remove donate JS code in favor of CSS-only solution
  sass/pages/_donate.scss
  static/donate.js
  templates/donate.html
Labels: C-Accessibility, C-Webdev, C-Code Quality, D-Straightforward

#1905 Extract News meta styling into a shared `heading-meta` and use it in Migrations
  sass/components/_heading-meta.scss
  sass/pages/_migration_guide.scss
  sass/pages/_news.scss
  sass/site.scss
  templates/shortcodes/migration_guides.md
  templates/shortcodes/release_notes.md
Labels: C-Webdev, C-Code Quality, D-Straightforward
