Repository bevyengine/bevy-website, pull requests merged in 2024-03, with the labels that each got.

#1068 Fix examples
  templates/example-webgpu.html
  templates/example.html
  templates/layouts/base.html
Labels: C-Bug, S-Ready-For-Final-Review, A-Examples

#1070 Group `typos` with linters in CI
  .github/workflows/ci.yml
Labels: A-Build-System

#1074 Add forgotten link to `Plugin` in quick start's getting started apps section
  content/learn/quick-start/getting-started/apps.md
Labels: S-Ready-For-Final-Review, A-Book, C-Correction

#1071 Update local CI running instructions for contributors
  CONTRIBUTING.md
Labels: A-Build-System, C-Content, C-Usability

#1073 Improve Bevy news feed
  content/news/2020-08-10-introducing-bevy/index.md
  content/news/2020-08-19-scaling-bevy/index.md
  content/news/2020-09-19-bevy-0.2/index.md
  content/news/2020-11-03-bevy-0.3/index.md
  content/news/2020-12-19-bevy-0.4/index.md
  content/news/2021-04-06-bevy-0.5/index.md
  content/news/2021-08-10-bevys-first-birthday/index.md
  content/news/2022-01-08-bevy-0.6/index.md
  content/news/2022-04-15-bevy-0.7/index.md
  content/news/2022-07-30-bevy-0.8/index.md
  content/news/2022-08-10-bevys-second-birthday/index.md
  content/news/2022-11-12-bevy-0.9/index.md
  content/news/2023-01-14-scaling-bevy-development/index.md
  content/news/2023-03-06-bevy-0.10/index.md
  content/news/2023-05-17-bevy-webgpu/index.md
  content/news/2023-07-09-bevy-0.11/index.md
  content/news/2023-08-10-bevys-third-birthday/index.md
  content/news/2023-09-21-community-reflection-on-bevys-third-year/index.md
  content/news/2023-11-04-bevy-0.12/index.md
  content/news/2023-12-12-sme-announcements/index.md
  content/news/2024-02-17-bevy-0.13/index.md
  sass/components/_footer.scss
  sass/site.scss
  static/assets/feed.svg
  static/assets/mastodon-logo-purple.svg
  templates/layouts/base.html
  templates/news-page.html
  templates/news.html
Labels: C-Enhancement, S-Ready-For-Final-Review, A-News, C-Usability

#1075 Assets search suggestions
  sass/pages/_assets.scss
  static/assets.js
  templates/assets.html
  templates/macros/assets.html
Labels: C-Enhancement, S-Ready-For-Final-Review, A-Assets

#1083 Update bevy version on `learn` chapters
  content/learn/quick-start/getting-started/_index.md
  content/learn/quick-start/getting-started/setup.md
  content/learn/quick-start/plugin-development.md
Labels: S-Ready-For-Final-Review, C-Correction

#1082 Docs: Fixed typo and a mistake in the code in plugins.md
  content/learn/quick-start/getting-started/plugins.md
Labels: S-Ready-For-Final-Review, C-Correction

#1081 Cache `generate-assets` output in CI
  .github/workflows/ci.yml
  .github/workflows/deploy.yml
Labels: C-Enhancement, S-Ready-For-Final-Review, A-Build-System

#1092 Bevy Foundation: announcement and foundation pages
  .djlintrc
  content/donate/_index.md
  content/donate/faq/index.md
  content/donate/foundation-sponsors.toml
  content/donate/individual-sponsors.toml
  content/donate/metrics.toml
  content/donate/tiers.toml
  content/foundation/_index.md
  content/foundation/budget/index.md
  content/foundation/bylaws/index.md
  content/foundation/meeting-minutes/2024-02-03/index.md
  content/foundation/meeting-minutes/_index.md
  content/news/2023-03-06-bevy-0.10/index.md
  content/news/2023-07-09-bevy-0.11/index.md
  content/news/2023-08-10-bevys-third-birthday/index.md
  content/news/2023-11-04-bevy-0.12/index.md
  content/news/2024-03-11-bevy-foundation/bevy_foundation.svg
  content/news/2024-03-11-bevy-foundation/index.md
  generate-community/src/bin/generate.rs
  sass/components/_sponsors.scss
  sass/pages/_donate.scss
  sass/pages/_features.scss
  sass/pages/_foundation.scss
  sass/site.scss
  static/assets/bevy_foundation.svg
  static/assets/sponsor_badges/bronze.svg
  static/assets/sponsor_badges/diamond.svg
  static/assets/sponsor_badges/gold.svg
  static/assets/sponsor_badges/patron.svg
  static/assets/sponsor_badges/platinum.svg
  static/assets/sponsor_badges/silver.svg
  static/assets/sponsor_badges/titanium.svg
  static/assets/sponsors/BFH.png
  static/assets/sponsors/Encultured.png
  static/assets/sponsors/Foresight_Spatial_Labs.svg
  static/assets/sponsors/Pixeljam.png
  static/assets/sponsors/VPSServer.png
  static/assets/sponsors/Wunder_Software_GmbH.png
  static/assets/sponsors/agile_perception.png
  static/assets/sponsors/embark.png
  static/assets/sponsors/keygen.png
  static/assets/sponsors/roids_logo.png
  static/assets/sponsors/timclicks.png
  static/assets/sponsors/vertex_studio.png
  static/donate.js
  templates/donate-community.html
  templates/donate.html
  templates/foundation.html
  templates/index.html
  templates/individual-sponsors.html
  templates/layouts/base.html
  templates/macros/numbers.html
  templates/page.html
  templates/sponsors.html
  templates/sponsorship-pledge.html
Labels: S-Ready-For-Final-Review, A-News, C-Content, S-Controversial

#1090 Use Javascript `mega-linter` flavor
  .github/workflows/ci.yml
  .mega-linter.yml
Labels: S-Ready-For-Final-Review, A-Build-System, C-Usability

#1106 Make the Query struct link work in getting started ECS page
  content/learn/quick-start/getting-started/ecs.md
Labels: C-Bug, S-Ready-For-Final-Review, A-Book

#1112 Fix authors of Bevy Foundation posts
  content/foundation/meeting-minutes/2024-02-03/index.md
  content/news/2024-03-11-bevy-foundation/index.md
Labels: C-Bug, S-Ready-For-Final-Review, A-Foundation

#1095 Fix cursor for corporate tier button
  sass/elements/_button.scss
  sass/site.scss
  templates/donate.html
Labels: C-Accessibility, S-Ready-For-Final-Review, A-Foundation

#1113 fix: book/getting-started doesn't redirect to quick-start
  content/learn/book/getting-started/_index.md
  content/learn/quick-start/getting-started/_index.md
Labels: C-Bug, S-Ready-For-Final-Review, A-Book, C-Webdev

#1079 Describe the MIT-Apache dual license in the quick start guide.
  content/learn/quick-start/introduction.md
Labels: S-Ready-For-Final-Review, A-Home, C-Correction

#1101 Github Actions improvements for `write-rustdoc-hide-lines` (v2)
  write-rustdoc-hide-lines/src/main.rs
Labels: S-Ready-For-Final-Review, A-Build-System, C-Usability

#1118 Fix `sync_donors.sh` permissions
  content/donate/sync_donors.sh
Labels: C-Bug, A-Build-System

#1089 Rewrite `generate-errors` and improve `learn/errors`
  Cargo.lock
  content/learn/links.toml
  generate-errors/.gitignore
  generate-errors/Cargo.toml
  generate-errors/README.md
  generate-errors/generate_errors.sh
  generate-errors/src/bin/generate.rs
  generate-errors/src/lib.rs
  templates/errors.html
  templates/layouts/base.html
Labels: C-Enhancement, S-Ready-For-Final-Review, A-Build-System, C-Usability

#1120 Make donor logos take up available height
  sass/components/_sponsors.scss
Labels: C-Webdev, A-Foundation

#1121 Improve logo size configurability and fix mobile scale
  .djlintrc
  content/donate/individual-sponsors.toml
  content/donate/tiers.toml
  sass/components/_sponsors.scss
  templates/individual-sponsors.html
  templates/sponsors.html
Labels: A-Foundation

#1077 `generate-community` improvements
  generate-community/Cargo.toml
  generate-community/src/bin/generate.rs
  generate-community/src/bin/validate.rs
  generate-community/src/lib.rs
Labels: S-Ready-For-Final-Review, A-Build-System, C-Code Quality

#1125 Remove extra backtick from `plugin-development.md`
  content/learn/quick-start/plugin-development.md
Labels: C-Correction

#1124 wasm examples: update the GitHub actions
  .github/workflows/build-wasm-examples.yml
  .github/workflows/update-screenshots.yml
Labels: C-Bug, C-Enhancement, S-Ready-For-Final-Review, A-Build-System
