Repository bevyengine/bevy-website, pull requests merged in 2025-06, with the labels that each got.

#2148 bevyengine.org -> bevy.org
  CONTRIBUTING.md
  README.md
  config.toml
  content/foundation/bylaws/index.md
  content/learn/contribute/helping-out/creating-examples.md
  content/learn/contribute/helping-out/opening-pull-requests.md
  content/learn/contribute/helping-out/writing-docs.md
  content/learn/contribute/introduction.md
  content/learn/contribute/project-information/bevy-organization.md
  content/learn/contribute/project-information/release-process.md
  content/learn/migration-guides/0.10-to-0.11.md
  content/learn/migration-guides/0.12-to-0.13.md
  content/learn/quick-start/introduction.md
  content/learn/quick-start/next-steps.md
  content/learn/quick-start/plugin-development.md
  content/news/2020-08-10-introducing-bevy/index.md
  content/news/2020-08-19-scaling-bevy/index.md
  content/news/2020-12-19-bevy-0.4/index.md
  content/news/2021-04-06-bevy-0.5/index.md
  content/news/2021-08-10-bevys-first-birthday/index.md
  content/news/2022-01-08-bevy-0.6/index.md
  content/news/2022-04-15-bevy-0.7/index.md
  content/news/2022-07-30-bevy-0.8/index.md
  content/news/2022-11-12-bevy-0.9/index.md
  content/news/2023-01-14-scaling-bevy-development/index.md
  content/news/2023-03-06-bevy-0.10/index.md
  content/news/2023-05-17-bevy-webgpu/index.md
  content/news/2023-07-09-bevy-0.11/index.md
  content/news/2023-09-21-community-reflection-on-bevys-third-year/index.md
  content/news/2023-11-04-bevy-0.12/index.md
  content/news/2024-02-17-bevy-0.13/index.md
  content/news/2024-07-04-bevy-0.14/index.md
  content/news/2024-08-10-bevys-fourth-birthday/index.md
  content/news/2024-09-10-dream-job/index.md
  content/news/2024-11-29-bevy-0.15/index.md
  content/news/2025-01-07-bevy-at-rust-week/index.md
  content/news/2025-04-24-bevy-0.16/index.md
  generate-assets/README.md
  generate-assets/src/lib.rs
  release-content/0.14/migration-guides/13080_Deprecate_dynamic_plugins.md
  release-content/0.14/release-notes/13121_Implement_filmic_color_grading.md
  release-content/0.14/release-notes/13123_Implement_a_SystemBuilder_for_building_SystemParams.md
  release-content/0.14/release-notes/new_math_primitives.md
  release-content/0.15/changelog.toml
  release-content/0.15/release-notes/14212_Component_Lifecycle_Hook__Observer_Trigger_for_replaced_va.md
  release-content/0.15/release-notes/14817_SystemParamBuilder__Support_dynamic_system_parameters.md
  release-content/0.15/release-notes/15085_Add_state_scoped_events.md
  release-content/0.15/release-notes/15184_Support_systems_that_take_references_as_input.md
  release-content/0.15/release-notes/15204_box_shadow.md
  release-content/0.15/release-notes/15361_Implement_volumetric_fog_support_for_both_point_lights_and.md
  release-content/0.16/release-notes/17648_mesh_tags.md
  release-content/0.16/release-notes/17953_Add_support_for_experimental_WESL_shader_source.md
  release-content/0.16/release-notes/gpu_tracing.md
  release-content/0.16/release-notes/occlusion_culling.md
  templates/foundation.html
  templates/layouts/base.html
Labels: C-Webdev

#2147 Fix immutable component code in 0.16 release notes
  release-content/0.16/release-notes/16372_Add_Immutable_Component_Support.md
Labels: A-News, C-Correction, S-Needs-Review, D-Trivial

#2145 Add a callout to the example pages if JavaScript is disabled
  templates/layouts/example.html
Labels: S-Ready-For-Final-Review, C-Webdev, A-Examples

#2152 Restructure Bevy Foundation Actions Without a Meeting and add new actions
  content/foundation/meeting-minutes/actions-without-meeting/index.md
  content/foundation/meeting-minutes/bevy-in-pixel-eagle-marketing/index.md
  content/foundation/meeting-minutes/bevy-in-pixel-eagle-marketing/pixel-eagle-marketing.png
  content/foundation/meeting-minutes/bevy-playground-logo-usage/bevy_playground_logo_usage.png
  content/foundation/meeting-minutes/bevy-playground-logo-usage/index.md
  content/foundation/meeting-minutes/board-meeting-2024-02-03/index.md
  content/foundation/meeting-minutes/buying-bevy-org-domain/bevy-org-domain.png
  content/foundation/meeting-minutes/buying-bevy-org-domain/index.md
  content/foundation/meeting-minutes/conference-allowance/conference-allowance.png
  content/foundation/meeting-minutes/conference-allowance/index.md
  content/foundation/meeting-minutes/deprecating-legacy-sponsors/deprecating_legacy_sponsors.png
  content/foundation/meeting-minutes/deprecating-legacy-sponsors/index.md
  content/foundation/meeting-minutes/hardware-for-benchmarking/hardware-for-benchmarking.png
  content/foundation/meeting-minutes/hardware-for-benchmarking/index.md
  content/foundation/meeting-minutes/hire-cart/hire-cart.png
  content/foundation/meeting-minutes/hire-cart/index.md
  content/foundation/meeting-minutes/increasing-alice-salary/increasing_alice_salary.png
  content/foundation/meeting-minutes/increasing-alice-salary/index.md
  content/foundation/meeting-minutes/initial-job-titles/index.md
  content/foundation/meeting-minutes/initial-job-titles/initial_job_titles.png
  content/foundation/meeting-minutes/more-relaxed-voting-rules/index.md
  content/foundation/meeting-minutes/more-relaxed-voting-rules/more_relaxed_voting_rules.png
  content/foundation/meeting-minutes/raise-alice-pay/index.md
  content/foundation/meeting-minutes/raise-alice-pay/raise-alice-pay.png
  content/foundation/meeting-minutes/recording-votes/index.md
  content/foundation/meeting-minutes/recording-votes/recording_who_voted.png
  content/foundation/meeting-minutes/repaying-cart/index.md
  content/foundation/meeting-minutes/repaying-cart/repaying_cart_initial_deposit.png
  content/foundation/meeting-minutes/sick-leave-documentation/index.md
  content/foundation/meeting-minutes/sick-leave-documentation/sick_leave_documentation_policy.png
  content/foundation/meeting-minutes/thera-as-eor/index.md
  content/foundation/meeting-minutes/thera-as-eor/thera_employer_of_record.png
Labels: S-Ready-For-Final-Review, C-Content, A-Foundation
