Repository bevyengine/bevy-website, pull requests merged in 2025-05, with the labels that each got.

#2125 Remove old failing tests from generate-assets and run tests in CI
  .github/workflows/ci.yml
  generate-assets/src/lib.rs
  generate-errors/download_errors.sh
  generate-errors/generate_errors.sh
  learning-code-examples/README.md
  learning-code-examples/examples/quick-start/getting_started_v3.rs
  learning-code-examples/examples/quick-start/getting_started_v7.rs
  learning-code-examples/examples/quick-start/getting_started_v9.rs
  learning-code-examples/validate_examples.sh
Labels: A-Build-System, S-Needs-Review, D-Modest

#2127 Move sentence into details section
  content/learn/quick-start/getting-started/setup.md
Labels: S-Ready-For-Final-Review, D-Trivial

#1949 Add an examples explanation contribution page
  content/learn/contribute/helping-out/explaining-examples.md
Labels: S-Ready-For-Final-Review, A-Contributing-Guide, X-Contentious

#2129 Add S-Needs-Reproduction to Contributing Guide
  content/learn/contribute/reference/triage.md
Labels: S-Ready-For-Final-Review, C-Content, A-Contributing-Guide, X-Uncontroversial

#2098 Show example explanation
  sass/components/_example.scss
  sass/components/_tabs.scss
  templates/layouts/example.html
Labels: S-Ready-For-Final-Review, C-Webdev, A-Examples

#2133 Update install instructions
  README.md
Labels: S-Ready-For-Final-Review, C-Usability, C-Docs, D-Trivial

#2131 Create "usage examples" category of first-party Bevy examples
  content/learn/contribute/helping-out/creating-examples.md
Labels: C-Feature, S-Ready-For-Final-Review, A-Contributing-Guide, X-Contentious

#2136 Add bluesky as social.
  generate-community/src/bin/generate.rs
  generate-community/src/lib.rs
  templates/donate-community.html
  templates/people.html
Labels: A-People, S-Needs-Review, X-Uncontroversial

#2137 iOS migration guide update
  release-content/0.16/migration-guides/14780_Link_iOS_example_with_rustc_and_avoid_C_trampoline.md
Labels: C-Content, A-Migration Guides, C-Correction, S-Needs-Review, D-Straightforward

#2138 Report issue with page option
  .github/ISSUE_TEMPLATE/docs.md
  templates/docs.html
Labels: C-Feature, S-Ready-For-Final-Review, A-Cross-Cutting
