Repository bevyengine/bevy-website, pull requests merged in 2025-10, with the labels that each got.

#2271 Replace unlicensed WGSL syntax definition with a licensed one
  syntaxes/README.md
  syntaxes/WGSL.sublime-syntax
Labels: S-Ready-For-Final-Review, C-Dependencies, D-Straightforward, A-Cross-Cutting

#2277 Fix indentation of headings in 0.17 migration guide
  content/learn/migration-guides/0.16-to-0.17.md
Labels: S-Ready-For-Final-Review, A-Migration Guides, C-Correction, D-Trivial

#2273 Update release process
  content/learn/contribute/project-information/release-process.md
Labels: S-Ready-For-Final-Review, A-Meta, C-Correction

#2278 Replace `On::original_entity()` in migration guide with `On::original_event_target()`
  content/learn/migration-guides/0.16-to-0.17.md
Labels: S-Ready-For-Final-Review, A-Migration Guides, C-Correction

#2280 Rename C-Enhancement to C-Feature
  content/learn/contribute/reference/triage.md
Labels: S-Ready-For-Final-Review, C-Correction, A-Contributing-Guide, D-Trivial
